exclude: ['posts']
url: https://fmarslan.com
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme
 - jekyll-sitemap
 - jekyll-paginate

remote_theme: jekyll/minima

#theme: minima
locale: "en-US"
title: "F.M. Arslan"
author:
  name: Fatih Mehmet ARSLAN
  email: contact@fmarslan.com
  type: person
  
description: >
  I'm a solution architect & software enginer.  

paginate: 20
show_excerpts: true
google_analytics: G-ZPHHT8GE5Z
permalink: /:categories/:year/:month/:day/:title:output_ext
paginate_path: /blog/:num

minima:
  skin: classic
  date_format: "%b %-d, %Y"
  social_links:
    twitter: FMArslan46
    github: fmarslan
    linkedin: fmarslan
