url: https://fmarslan.com
locale: "en-US"
title: "F.M. Arslan"
description: >
  I'm a solution architect & software engineer.
keywords:
  - Fatih Mehmet Arslan
  - solution architect
  - software engineer
  - cloud architecture
social:
  name: "Fatih Mehmet Arslan"
  links:
    - https://www.linkedin.com/in/fmarslan
    - https://github.com/fmarslan
    - https://fmarslan.medium.com

author:
  name: Fatih Mehmet ARSLAN
  email: contact@fmarslan.com
  type: person
  job_title: Solution Architect & Software Engineer

share_image: /android-chrome-512x512.png

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

markdown: kramdown
permalink: /:categories/:year/:month/:day/:title:output_ext
paginate: 20
paginate_path: /blog/:num
show_excerpts: true
google_analytics: G-ZPHHT8GE5Z
future: true

sass:
  sass_dir: _sass
  style: compressed

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      lang: tr-TR
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
      lang: en-US

navigation:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
  - title: Resume
    url: /cv/

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - _site
